sudo: required
services:
- docker
language: bash
script:
- docker run --rm --privileged multiarch/qemu-user-static:register --reset
- export TAG=`if [[ $TRAVIS_PULL_REQUEST == "false" ]] && [[ $TRAVIS_BRANCH == "master"
  ]]; then echo "latest"; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi`
- export REPO=zepp/rpi-socat
- docker build -t $REPO:$TAG .
after_success:
- docker login -u="$HUB_USER" -p="$HUB_PASS"
- if [[ $TRAVIS_PULL_REQUEST == "false" ]] && [[ $TRAVIS_BRANCH == "master" ]]; then
  docker tag $REPO:$TAG $REPO:$TRAVIS_BUILD_NUMBER; docker push $REPO:$TRAVIS_BUILD_NUMBER;
  fi
- docker push $REPO:$TAG
notifications:
  slack:
    rooms:
      secure: qEph8labzLCBGTAdgVd1HlN2VlPs5hSm4iJGySUaBFB1nJJKKkUiZINsJ9NYntAJ/b+0TCJUV/HwyINibTIXD6W38JqVXxExIPfjRAjOtELP9fA21eDrJMsLOUkcNeuSj5Eqi287b2R14jlACQKQEg8D1AQNfvXXB/eKFVHl5HPC0scyse7xQC5fvpxFVvKKH4Isfdw1pELGYzaFMZm/GWAWCeeeYMHwg/R0bSWFsT9Yb1qGI3J6mljnwg5MyqBbKAEnqbfZ9/fLzCjAfKsyTQ9fSFmcwwh95hHGk5JEgAslkZxNmhXMwRNGEMiveNFsDJJhf4fpdZ8db750kZuVvnGiFjCizzL7ArDcfAhWbUv/woo8T/MXPk9psIRG2gLCpi/RYJyF3QjekU4VcfRDU722Ph2vnj/B179K43VyQIHF06lot8lr2YKCMCr2V0SSEq3BYjITsxB9BcIWYOUYpxXjiiqYGhqDP5sRrNgoBX9LYQQijArKN/fKcsQ7/7X2PbWCNkNCc1OGmibET7sa5t6tteEgB81XiFjEI0DgMYxLHz5fDv9yuizBFioIjpYncMmOwQNvLAToJx5NPHL10yPZkY1pVmmv4ixGKMXAMnIiPYwMF8umaYmQCh6gPTebehKBsmcRF/M3gnjGjViVrGmSlmj0Zjw6xpIkAlH6Rtk=
    template:
    - "%{repository} (%{commit}) : %{message} "
    - 'Build number: %{build_number} - Commit message: %{commit_message}'
    - 'Runtime: %{elapsed_time}'
    - 'Build details: %{build_url}'
